### PR TITLE
Issue # 3 - Convert to Python 3

### PR DESCRIPTION
**Pull request by paqman85**
I refactored your code to Python 3 and styled to pep8. I also added a .gitignore file with standard python ignores.

### CODE REVIEW

**Comment by adigeo** [comment]
Due to vacations this will be replied later.

**Comment by danpascu** [comment]
A few comments about this pull request:

1. Keep different changes in as different patches. This one mixes converting to python 3 with PEP-8 styling.

2. python-application is already PEP-8 compliant with the exception of the 80 column rule where we use a 200 column rule. I won't accept the changes to 80 character lines so unless there are other PEP-8 violations the PEP-8 changes can be removed.

3. This migration seems to be a run-of-the-mill 2to3 conversion. Unfortunately that is not enough:

   - There are certain classes that implement mapping types that need to be converted to the python3 semantics. This needs to be carefully considered as not only it breaks backward compatibility (which we can probably somewhat overlook considering the code moves from python 2 to python 3), but it also breaks some of the promises the class made (I'm talking about `weakobjectmap` here but there may be others). 
 
   - The execute_once decorator no longer works as the semantics of methods and class methods changed and the simple replacement of `im_self` and `im_class` with `__self__` and `__class__` is not enough.
 
   - The **debug.timing** module needs to be reevaluated as it uses byte code manipulation which might not be valid anymore.
 
   - **debug.memory** might also be affected.

**Comment by gytis-ivaskevicius** [comment]
Bump. https://pythonclock.org/ :cold_sweat:

**Comment by adigeo** [comment]
https://github.com/AGProjects/python3-application

**Pull request closed without merging**
